### ISSUE TITLE
Release Workflow has outdated environment variable setting

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-api-python#150]
## Bug Report

This type of environment setting is out of date:
`run: echo ::set-env name=PACKAGE_VERSION::$(echo $VERSION | poetry version | cut -c23-27)`
Switch to updated version

https://github.com/microsoft/electionguard-api-python/blob/3c9154b091bbe88a5aa478d8f1eb593484fbef51/.github/workflows/release.yml#L73

**Comment by shepherdjay** [comment]
Looks like something I can help with - reading up on the github deprecation notice.
