### ISSUE TITLE
✨  Upload Ballot API

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-api-python#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

This is to ensure a ballot can be uploaded into the api for a specific open election. This should reject invalid ballots. Although this is just for the upload or post of the ballot. This card should also include the get and list so this can be tested. 

- [x] Ensure Ballot Upload API works with newer python 1.3 update.

**Comment by gagandeepp** [comment]
interested

**Comment by lprichar** [comment]
I split this ticket out into #213 #214 and #215 to reduce scope
