### ISSUE TITLE
🐞 Require Authentication for All Endpoints

### ISSUE THREAD

**Issue by lprichar** [microsoft/electionguard-api-python#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now you can hit most endpoints without authenticating

### Expected Behavior

Every page except for the login page (`{{mediator-url}}/api/{{version}}/auth/login`) and ping (`{{mediator-url}}/api/{{version}}/ping`, `{{guardian-url}}/api/{{version}}/ping`) should require authentication, and should probably only allow admins unless they're explicitly opened up to others.

Ideally this should be "opt out" behavior, so any new endpoints created will require authentication by an admin unless explicitly marked as open to the world.

### Environment

```markdown
- OS:
```

**Comment by colleenirt** [comment]
This will not be worked or considered for 1.0.  A new issue will be created if needed in the future.
